<?xml version="1.0" encoding="utf-8"?><Database Name="NFC" Class="MappingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PlaceAccess" Member="PlaceAccesses">
    <Type Name="PlaceAccess">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlaceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExpireDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Place_PlaceAccess" Member="Place" ThisKey="PlaceID" OtherKey="Id" Type="Place" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="User_PlaceAccess" Member="User" ThisKey="UserID" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Places" Member="Places">
    <Type Name="Place">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlaceTitle" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Place_PlaceAccess" Member="PlaceAccesses" ThisKey="Id" OtherKey="PlaceID" Type="PlaceAccess" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NFC" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExpireDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="User_PlaceAccess" Member="PlaceAccesses" ThisKey="Id" OtherKey="UserID" Type="PlaceAccess" />
      <Association Name="User_AccessLog" Member="AccessLogs" ThisKey="Id" OtherKey="UserID" Type="AccessLog" />
    </Type>
  </Table>
  <Table Name="dbo.AccessLog" Member="AccessLogs">
    <Type Name="AccessLog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccessDetail" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccessDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="User_AccessLog" Member="User" ThisKey="UserID" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>